language: php

php:
    - 5.3
    - 5.4

before_script:
    - composer install
    - psql -c 'create database ouzo_test' -U postgres
    - psql -v ON_ERROR_STOP=1 -e -U postgres -f test/test-db/recreate_schema.sql ouzo_test
    
script: phpunit --configuration phpunit.xml
